### ISSUE TITLE
README.md needs updating

### ISSUE THREAD

**Issue by Joaalslie** [EdvardPedersen/AssignmentBalancer#1]
# TODO :hammer: 
* The readme does not mention how to run the program correctly. :turtle: 
* It is not made clear in the readme that the user needs to include the T.A's file when running the program.  

## Suggestion :pencil2: 
* In the "How to use" section, change the suggestion on how to run the program to:
  * 'python balance.py -l students.csv -t groups.csv' 
* Instead of the previous: 
  * 'python balance.py -l students.csv'

**Comment by EdvardPedersen** [comment]
Change implemented
